site_name: Truck Counting
site_url: https://github.com/beethogedeon/truck-counting
repo_url: https://github.com/beethogedeon/truck-counting
edit_uri: "https://github.com/beethogedeon/truck-counting/edit/main/docs"

theme:
  name: material
  language: en
  features:
    - navigation.instant
  palette:
    primary: black
    accent: light blue

nav:
  - Home: index.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: 🔗

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/beethogedeon
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/beethogedeon
      name: GitHub
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/beethogedeon
      name: GitLab
    - icon: fontawesome/solid/code
      link: https://profile.codersrank.io/user/beethogedeon
      name: Codersrank
    - icon: fontawesome/brands/dev
      link: https://dev.to/beethogedeon
      name: Dev.to
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/8921443/beethogedeon
      name: Stack Overflow
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/beethogedeon
      name: Research Gate
    - icon: fontawesome/brands/medium
      link: https://medium.com/@beethogedeon
      name: Medium
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/beethogedeon
      name: Twitter
    - icon: fontawesome/brands/telegram
      link: https://t.me/beethogedeon
      name: Telegram
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/beethogedeon
      name: Facebook
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/beethogedeon
      name: Instagram
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/beethogedeon
      name: Youtube
    - icon: fontawesome/solid/paper-plane
      link: mailto:beethogedeon@gmail.com
      name: Email
